dubbo:
  application:
    name: product-service
  registry:
    protocol: zookeeper
    address: 192.168.142.137:2181
  protocol:
    port: 28810

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v17?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

